//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp5
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int KeyId { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public string Number { get; set; }
        public int AcrossTheFloor { get; set; }
        public int HeightFromTheFloor { get; set; }
        public int Angle { get; set; }
        public double Time { get; set; }
        public int Price { get; set; }
        public string JobType { get; set; }
        public int EighteenMDF { get; set; }
        public int TwelveMDF { get; set; }
        public int NineMDF { get; set; }
        public int Runners { get; set; }
        public int PushToOpen { get; set; }
        public int ThreeBy { get; set; }
        public int Paint { get; set; }
        public Nullable<bool> Agreed { get; set; }
        public Nullable<System.DateTime> QuoteDate { get; set; }
        public Nullable<System.DateTime> AgreedDate { get; set; }
        public Nullable<bool> Finished { get; set; }
    
        public virtual FinishedTable FinishedTable { get; set; }
    }
}
