//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp5
{
    using System;
    using System.Collections.Generic;
    
    public partial class FinishedTable
    {
        public int KeyId { get; set; }
        public Nullable<System.DateTime> finishDate { get; set; }
        public Nullable<float> timeTaken { get; set; }
        public Nullable<bool> payedBy { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
