//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp5
{
    using System;
    using System.Collections.Generic;
    
    public partial class receipt
    {
        public int id { get; set; }
        public string supplier { get; set; }
        public Nullable<double> spent { get; set; }
        public Nullable<System.DateTime> dateBought { get; set; }
    }
}
